### ISSUE TITLE
Use openstreetmap is not working

### ISSUE THREAD

**Issue by albo1337** [apptreesoftware/flutter_map#166]
Hey! I wanted to use open street map as tile layer options but this is not working:

```
            FlutterMap(
                options: MapOptions(
                  center: latLng != null ? latLng : LatLng(47.767097, 8.872239),
                  zoom: 16.0,
                ),
                layers: [
                  TileLayerOptions(
                    urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  ),
                  MarkerLayerOptions(
                    markers: [
                      Marker(
                        width: 80.0,
                        height: 80.0,
                        point: latLng != null ? latLng : LatLng(47.767097, 8.872239),
                        builder: (ctx) => Container(
                              child: Icon(
                                FontAwesomeIcons.mapMarker,
                                color: IHGColors.accentColor,
                              ),
                            ),
                      ),
                    ],
                  ),
                ],
              ),
```

The URL is not correct and I receive the following error:

```
I/flutter (15953): Exception: HTTP request failed, statusCode: 404,
I/flutter (15953): https://a.tile.openstreetmap.org/20/550046/365602.png
I/flutter (15953): 
I/flutter (15953): When the exception was thrown, this was the stack:
I/flutter (15953): #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:492:7)
I/flutter (15953): <asynchronous suspension>
I/flutter (15953): #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:471:14)
I/flutter (15953): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:86)
I/flutter (15953): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
I/flutter (15953): #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:63)
I/flutter (15953): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (15953): #6      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:265:30)
I/flutter (15953): #7      _ImageProviderResolver.resolve (package:flutter/src/widgets/fade_in_image.dart:333:29)
I/flutter (15953): #8      _FadeInImageState._resolveImage (package:flutter/src/widgets/fade_in_image.dart:408:20)
I/flutter (15953): #9      _FadeInImageState.didChangeDependencies (package:flutter/src/widgets/fade_in_image.dart:390:5)
I/flutter (15953): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3824:12)
I/flutter (15953): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (15953): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (15953): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (15953): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (15953): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (15953): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
I/flutter (15953): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (15953): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (15953): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (15953): #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (15953): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (15953): #22     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4563:32)
I/flutter (15953): #23     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4953:17)
I/flutter (15953): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (15953): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (15953): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (15953): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (15953): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (15953): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
I/flutter (15953): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (15953): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (15953): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (15953): #33     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (15953): #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (15953): #35     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (15953): #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (15953): #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (15953): #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (15953): #39     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (15953): #40     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (15953): 
I/flutter (15953): Image provider: NetworkImage("https://.tile.openstreetmap.org/20/550046/365602.png", scale: 1.0)
I/flutter (15953): Image key: NetworkImage("https://.tile.openstreetmap.org/20/550046/365602.png", scale: 1.0)
```
I have no idea what the {s} in the url stands for. Could anyone please help me?

**Comment by albo1337** [comment]
Got it.... subdomains were missing:

```
              FlutterMap(
                options: MapOptions(
                  center: latLng != null ? latLng : LatLng(47.767097, 8.872239),
                  zoom: 16.0,
                ),
                layers: [
                  TileLayerOptions(
                    urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                    subdomains: ['a', 'b', 'c'],
                  ),
                  MarkerLayerOptions(
                    markers: [
                      Marker(
                        width: 80.0,
                        height: 80.0,
                        point: latLng != null ? latLng : LatLng(47.767097, 8.872239),
                        builder: (ctx) => Container(
                              child: Icon(
                                FontAwesomeIcons.mapMarker,
                                color: IHGColors.accentColor,
                              ),
                            ),
                      ),
                    ],
                  ),
                ],
              ),
```
